import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { ArrowRight, Bot, Check, FileCheck2, FileImage, Film, Fingerprint, History, ImageIcon, Info, Link2, Mic2, SearchCheck, ShieldCheck, Sparkles, Users } from "lucide-react";
import { Button } from "@/components/ui/button";
import { MediaUpload } from "@/components/media-upload";
import { DashboardMockup, HeroVerificationVisual, StepIcon } from "@/components/verification-visuals";
import { ResultDashboard } from "@/components/result-dashboard";
import { demoAnalysis } from "@/lib/demo-analysis";

export const Route = createFileRoute("/")({
  head: () => ({ meta: [
    { title: "AI Ano — Verify Digital Media" },
    { name: "description", content: "Detect, understand, and verify potentially AI-generated or manipulated images before you trust or share them." },
    { property: "og:title", content: "AI Ano — Verify Digital Media" },
    { property: "og:description", content: "Evidence-led AI media verification for journalists, researchers, and everyday users." },
    { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
  ]}), component: HomePage,
});

const features = [
  [Fingerprint, "AI Detection", "Identify signals associated with AI-generated content."],
  [SearchCheck, "Media Forensics", "Analyze visual, audio, and technical inconsistencies."],
  [Bot, "Explainable AI", "Understand why the system reached its assessment."],
  [Link2, "Source Verification", "Trace available sources and compare surrounding context."],
  [History, "Evidence Timeline", "See how available versions of media relate to one another."],
  [FileCheck2, "Verification Reports", "Generate a structured report with analysis and supporting evidence."],
] as const;

function SectionHeading({ eyebrow, title, copy }: { eyebrow?: string; title: string; copy?: string }) { return <div className="mx-auto max-w-2xl text-center">{eyebrow && <p className="text-xs font-extrabold uppercase text-primary">{eyebrow}</p>}<h2 className="mt-2 text-3xl font-extrabold sm:text-4xl">{title}</h2>{copy && <p className="mt-4 text-sm leading-7 text-muted-foreground sm:text-base">{copy}</p>}</div>; }

function HomePage() {
  const navigate = useNavigate({ from: "/" });
  return <main>
    <section className="relative overflow-hidden"><div className="absolute inset-x-0 top-0 -z-10 h-[720px] bg-sky-soft/70"/><div className="mx-auto grid max-w-7xl items-center gap-10 px-5 pb-20 pt-8 sm:px-8 lg:grid-cols-[1.03fr_.97fr] lg:pb-28 lg:pt-10"><div><span className="inline-flex items-center gap-2 rounded-full border border-primary/15 bg-card px-3 py-1.5 text-[11px] font-extrabold text-primary shadow-sm"><ShieldCheck className="size-3.5"/>AI ANO?</span><h1 className="mt-6 max-w-2xl text-5xl font-extrabold leading-[1.08] sm:text-6xl lg:text-7xl">Can You Trust<br/>What You <span className="text-primary">See?</span></h1><p className="mt-6 max-w-xl text-base leading-8 text-muted-foreground sm:text-lg">Analyze images, audio, and video for signs of AI generation, manipulation, and misleading context.</p><div className="mt-8 flex flex-wrap gap-3"><Button size="lg" asChild><Link to="/analyze">Analyze Media <ArrowRight/></Link></Button><Button size="lg" variant="outline" asChild><a href="#how-it-works">See How It Works</a></Button></div><p className="mt-7 flex items-center gap-2 text-xs font-semibold text-muted-foreground"><Check className="size-4 text-success"/>Builds evidence, not just predictions.</p></div><HeroVerificationVisual/></div></section>
    <section className="relative z-10 mx-auto -mt-8 max-w-4xl px-5 sm:px-8"><MediaUpload compact onAnalyze={() => navigate({ to: "/analyze" })}/></section>

    <section id="how-it-works" className="scroll-mt-24 px-5 py-28 sm:px-8"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="A clearer path to context" title="How Does AI Ano Work?" copy="Four simple steps to understand suspicious media."/><div className="relative mt-14 grid gap-8 md:grid-cols-4"><div className="absolute left-[12%] right-[12%] top-8 hidden border-t border-dashed border-primary/30 md:block"/>{[["UPLOAD","Upload an image, audio file, video, or supported media URL."],["ANALYZE","The pipeline examines AI-generation and manipulation signals."],["UNDERSTAND","GenAI turns technical evidence into a simple explanation."],["VERIFY","Review sources, context, evidence, and the final assessment."]].map(([title,copy],i)=><article key={title} className="relative flex flex-col items-center text-center"><span className="absolute -top-3 right-[calc(50%-44px)] z-20 grid size-7 place-items-center rounded-full bg-foreground text-[10px] font-bold text-background">0{i+1}</span><StepIcon type={i}/><h3 className="mt-5 text-sm font-extrabold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{copy}</p></article>)}</div></div></section>

    <section className="bg-sky-soft px-5 py-24 sm:px-8"><div className="mx-auto max-w-6xl"><SectionHeading title="Analyze More Than Just Images" copy="A verification foundation designed to expand across the media landscape."/><div className="mt-12 grid gap-4 md:grid-cols-3">{[[ImageIcon,"IMAGE","AI-generated images, edited photos, synthetic faces",true],[Mic2,"AUDIO","AI-generated voices, cloned speech, manipulated recordings",false],[Film,"VIDEO","Deepfakes, face swaps, synthetic video, manipulated footage",false]].map(([Icon,title,copy,active])=><article key={title as string} className={`relative rounded-xl border p-6 transition-transform hover:-translate-y-1 ${active ? 'border-primary bg-primary text-primary-foreground shadow-button' : 'border-border bg-card'}`}><div className={`grid size-12 place-items-center rounded-xl ${active ? 'bg-primary-foreground/15' : 'bg-accent text-primary'}`}><Icon className="size-6"/></div><h3 className="mt-5 font-extrabold">{title as string}</h3><p className={`mt-2 text-sm leading-6 ${active ? 'text-primary-foreground/80' : 'text-muted-foreground'}`}>{copy as string}</p><span className={`mt-5 inline-block rounded-full px-2.5 py-1 text-[9px] font-extrabold ${active ? 'bg-primary-foreground/15' : 'bg-muted text-muted-foreground'}`}>{active ? 'AVAILABLE NOW' : 'COMING SOON'}</span></article>)}</div></div></section>

    <section id="features" className="scroll-mt-24 px-5 py-28 sm:px-8"><div className="mx-auto max-w-7xl"><SectionHeading eyebrow="Built for careful decisions" title="Everything You Need to Verify Digital Media"/><div className="mt-12 grid gap-4 md:grid-cols-2 lg:grid-cols-3">{features.map(([Icon,title,copy])=><article key={title} className="group rounded-xl border border-border bg-card p-6 transition-all hover:-translate-y-1 hover:border-primary/25 hover:shadow-card"><div className="grid size-11 place-items-center rounded-lg bg-accent text-primary transition-colors group-hover:bg-primary group-hover:text-primary-foreground"><Icon/></div><h3 className="mt-5 text-lg font-extrabold">{title}</h3><p className="mt-2 text-sm leading-6 text-muted-foreground">{copy}</p></article>)}</div></div></section>

    <section className="bg-sky-soft px-5 py-24 sm:px-8"><div className="mx-auto grid max-w-7xl items-center gap-12 lg:grid-cols-[1.05fr_.95fr]"><DashboardMockup/><div><p className="text-xs font-extrabold text-primary">EVIDENCE, NOT JUST OUTPUT</p><h2 className="mt-3 text-4xl font-extrabold">Not Just a Score</h2><p className="mt-5 text-base leading-8 text-muted-foreground">AI Ano doesn’t simply tell users that media is suspicious. It shows the evidence behind the assessment and explains what those signals mean.</p><ul className="mt-7 space-y-4">{['Evidence-based assessment','Human-readable explanation','Source and context verification'].map((item)=><li key={item} className="flex items-center gap-3 text-sm font-bold"><span className="grid size-6 place-items-center rounded-full bg-success/15 text-success"><Check className="size-3.5"/></span>{item}</li>)}</ul><Button className="mt-8" size="lg" asChild><Link to="/analyze">Try an Analysis <ArrowRight/></Link></Button></div></div></section>

    <section className="px-5 py-28 sm:px-8"><div className="mx-auto max-w-6xl"><SectionHeading eyebrow="Example analysis" title="Understand the Evidence" copy="See how individual signals contribute to an explainable, probabilistic assessment."/><div className="mt-12"><ResultDashboard result={demoAnalysis} example/></div></div></section>

    <section className="bg-sky-soft px-5 py-24 sm:px-8"><div className="mx-auto grid max-w-6xl gap-8 lg:grid-cols-[.72fr_1.28fr] lg:items-center"><div><span className="grid size-14 place-items-center rounded-xl bg-primary text-primary-foreground shadow-button"><Sparkles/></span><p className="mt-6 text-xs font-extrabold text-primary">GENAI-POWERED EXPLANATION</p><h2 className="mt-3 text-3xl font-extrabold">AI That Explains Its Reasoning</h2><p className="mt-4 text-sm leading-7 text-muted-foreground">GenAI communicates structured detector evidence in clear language. It does not invent detection results.</p></div><div className="rounded-2xl border border-border bg-card p-6 shadow-card sm:p-8"><p className="font-extrabold">Why was this media flagged?</p><p className="mt-5 text-sm leading-7 text-muted-foreground">“{demoAnalysis.explanation}”</p><div className="mt-5 flex items-center gap-2 border-t border-border pt-5 text-xs font-semibold text-muted-foreground"><Info className="size-4 text-primary"/>Always review the evidence and source context.</div></div></div></section>

    <section className="px-5 py-28 sm:px-8"><div className="mx-auto max-w-6xl"><SectionHeading eyebrow="Source and context" title="Where Did This Media Come From?" copy="Follow the available trail without confusing popularity with provenance."/><div className="mt-12 grid gap-0 md:grid-cols-5">{demoAnalysis.sourceVerification.timeline.map((item,i)=><div key={item.label} className="relative flex gap-4 pb-7 md:block md:text-center"><div className="relative z-10 grid size-12 shrink-0 place-items-center rounded-xl bg-accent text-primary">{i===0?<SearchCheck/>:i===4?<ShieldCheck/>:<ArrowRight/>}</div>{i<4&&<div className="absolute left-6 top-12 h-[calc(100%-1.5rem)] w-px bg-primary/25 md:left-1/2 md:top-6 md:h-px md:w-full"/>}<div className="md:mt-5"><h3 className="text-sm font-extrabold">{item.label}</h3><p className="mt-2 text-xs leading-5 text-muted-foreground">{item.detail}</p></div></div>)}</div><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{['Source URL','Publication date','Matching media','Context comparison','Caption differences'].map(label=><div key={label} className="rounded-lg border border-border bg-card p-4 text-center text-xs font-bold">{label}</div>)}</div></div></section>

    <section id="about" className="scroll-mt-24 bg-sky-soft px-5 py-24 sm:px-8"><div className="mx-auto max-w-6xl"><SectionHeading title="Verification Built for Real Decisions"/><div className="mt-12 grid gap-4 md:grid-cols-3">{[[FileCheck2,'JOURNALISTS','Verify media before publishing stories.'],[SearchCheck,'RESEARCHERS','Investigate synthetic media and source context.'],[Users,'EVERYDAY USERS','Check suspicious content before sharing it.']].map(([Icon,title,copy])=><article key={title as string} className="rounded-xl border border-border bg-card p-6"><Icon className="size-7 text-primary"/><h3 className="mt-5 font-extrabold">{title as string}</h3><p className="mt-3 text-sm text-muted-foreground">{copy as string}</p></article>)}</div></div></section>

    <section className="px-5 py-24 sm:px-8"><div className="mx-auto grid max-w-6xl gap-10 rounded-2xl bg-foreground p-8 text-background md:grid-cols-[1fr_1fr] lg:p-12"><div><p className="text-xs font-extrabold text-sky">RESPONSIBLE VERIFICATION</p><h2 className="mt-3 text-3xl font-extrabold">AI Detection Is Not Absolute Proof</h2><p className="mt-5 text-sm leading-7 text-background/70">AI Ano provides a probabilistic assessment based on available evidence. A high-risk score does not automatically prove that media is fake, and a low-risk score does not guarantee authenticity.</p></div><div className="space-y-3">{['Evidence over assumptions','Transparency over black-box verdicts','Verification over blind trust'].map((item,i)=><div key={item} className="flex items-center gap-4 rounded-xl bg-background/10 p-4"><span className="grid size-8 place-items-center rounded-full bg-primary text-xs font-bold text-primary-foreground">0{i+1}</span><span className="font-bold">{item}</span></div>)}</div></div></section>

    <section className="px-5 pb-24 sm:px-8"><div className="mx-auto max-w-7xl overflow-hidden rounded-2xl bg-primary px-6 py-16 text-center text-primary-foreground shadow-button sm:px-12"><h2 className="text-3xl font-extrabold sm:text-4xl">Before You Trust It, Verify It.</h2><p className="mx-auto mt-4 max-w-xl text-sm leading-7 text-primary-foreground/80">Analyze suspicious media and understand the evidence behind it.</p><Button asChild size="lg" variant="secondary" className="mt-7"><Link to="/analyze">Analyze Media <ArrowRight/></Link></Button></div></section>
  </main>;
}